# Generated by Django 3.2.21 on 2023-09-11 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionUnca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('nombre', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChampiongralUnca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('nombre', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeporteUnca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('nombre', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoUnca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Nombresanjuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sanjuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TablaPosicionesUnca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('partidos_jugados', models.PositiveIntegerField(default=0)),
                ('partidos_ganados', models.PositiveIntegerField(default=0)),
                ('partidos_empatados', models.PositiveIntegerField(default=0)),
                ('partidos_perdidos', models.PositiveIntegerField(default=0)),
                ('goles_favor', models.PositiveIntegerField(default=0)),
                ('goles_contra', models.PositiveIntegerField(default=0)),
                ('diferencia_goles', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpunca.equipounca')),
            ],
        ),
        migrations.CreateModel(
            name='PosicionUnca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_futbol_masc', models.IntegerField(default=0)),
                ('puntos_futbol_fem', models.IntegerField(default=0)),
                ('puntos_basket_masc', models.IntegerField(default=0)),
                ('puntos_basket_fem', models.IntegerField(default=0)),
                ('puntos_volley_masc', models.IntegerField(default=0)),
                ('puntos_volley_fem', models.IntegerField(default=0)),
                ('puntos_piki', models.IntegerField(default=0)),
                ('puntos_fifa', models.IntegerField(default=0)),
                ('puntos_poker', models.IntegerField(default=0)),
                ('puntos_truco', models.IntegerField(default=0)),
                ('puntos_ajedrez', models.IntegerField(default=0)),
                ('puntos_pingpong', models.IntegerField(default=0)),
                ('puntos_hinchada', models.IntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpunca.equipounca')),
            ],
        ),
        migrations.CreateModel(
            name='PartidoUnca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.PositiveIntegerField(blank=True, null=True)),
                ('goles_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('partido_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('fase_partido', models.CharField(blank=True, max_length=99, null=True)),
                ('deporte', models.CharField(blank=True, choices=[('FUTBOL_MASCULINO', 'Fútbol Masculino'), ('FUTBOL_FEMENINO', 'Fútbol Femenino'), ('BASKET_MASCULINO', 'Básquet Masculino'), ('BASKET_FEMENINO', 'Básquet Femenino'), ('VOLLEY_MASCULINO', 'Vóley Masculino'), ('VOLLEY_FEMENINO', 'Vóley Femenino'), ('PIKI', 'Piki'), ('FIFA23', 'FIFA 23'), ('PING_PONG', 'Ping Pong'), ('POKER', 'Poker'), ('AJEDREZ', 'Ajedrez'), ('TRUCO', 'Truco')], max_length=50, null=True)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='cpunca.equipounca')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='cpunca.equipounca')),
            ],
        ),
        migrations.CreateModel(
            name='EventosUnca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('GOOOOL', 'Gol local'), ('GOOOL', 'Gol visitante'), ('PUNTO', 'Punto local'), ('PUNTO ', 'Punto visitante'), ('TARJETA ROJA', 'Tarjeta roja local'), ('TARJETA ROJA ', 'Tarjeta roja visitante'), ('TARJETA AMARILLA', 'Tarjeta amarilla local'), ('TARJETA AMARILLA ', 'Tarjeta amarilla visitante')], max_length=100)),
                ('jugadores', models.CharField(max_length=150)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpunca.partidounca')),
            ],
        ),
        migrations.CreateModel(
            name='EventoPartidoUnca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INICIO DEL PARTIDO', 'Inicio del partido'), ('PENDIENTE', 'Pendiente'), ('FINAL DEL PARTIDO', 'Fin del partido')], max_length=100)),
                ('minuto', models.PositiveIntegerField(blank=True, null=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpunca.partidounca')),
            ],
        ),
        migrations.CreateModel(
            name='CampeonUnca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeon_2016', models.IntegerField(default=0)),
                ('campeon_2017', models.IntegerField(default=0)),
                ('campeon_2018', models.IntegerField(default=0)),
                ('campeon_2019', models.IntegerField(default=0)),
                ('campeon_2022', models.IntegerField(default=0)),
                ('campeon_2023', models.IntegerField(default=0)),
                ('total_campeonatos', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpunca.equipounca')),
            ],
        ),
    ]
