# Generated by Django 3.2.21 on 2023-09-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpunca', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nombresanjuan',
        ),
        migrations.DeleteModel(
            name='Sanjuan',
        ),
    ]
