# Generated by Django 3.2.21 on 2024-08-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpunca', '0002_auto_20230911_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidounca',
            name='deporte',
            field=models.CharField(blank=True, choices=[('FUTBOL_FEMENINO', 'Fútbol Femenino'), ('FUTBOL_MASCULINO', 'Fútbol Masculino'), ('FUTSAL_FEMENINO', 'Fútsal Femenino'), ('FUTSAL_MASCULINO', 'Fútsal Masculino'), ('HANDBALL_FEMENINO', 'Handball Femenino'), ('HANDBALL_MASCULINO', 'Handball Masculino'), ('VOLLEY_FEMENINO', 'Volley Femenino'), ('VOLLEY_MASCULINO', 'Volley Masculino'), ('BASKET_FEMENINO', 'Básquet Femenino'), ('BASKET_MASCULINO', 'Básquet Masculino'), ('FUTBOL_UNIVERSITARIO', 'Fútbol Universitario'), ('PIKI', 'Piki'), ('AJEDREZ', 'Ajedrez'), ('PING_PONG', 'Ping Pong')], max_length=50, null=True),
        ),
    ]
