# Generated by Django 3.2.21 on 2024-08-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpunca', '0003_alter_partidounca_deporte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posicionunca',
            old_name='puntos_fifa',
            new_name='puntos_atletismo',
        ),
        migrations.RenameField(
            model_name='posicionunca',
            old_name='puntos_hinchada',
            new_name='puntos_ciclismo',
        ),
        migrations.RenameField(
            model_name='posicionunca',
            old_name='puntos_poker',
            new_name='puntos_futbol_universitario',
        ),
        migrations.RenameField(
            model_name='posicionunca',
            old_name='puntos_truco',
            new_name='puntos_futsal_fem',
        ),
        migrations.AddField(
            model_name='posicionunca',
            name='puntos_futsal_masc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posicionunca',
            name='puntos_handball_fem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posicionunca',
            name='puntos_handball_masc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partidounca',
            name='deporte',
            field=models.CharField(blank=True, choices=[('FUTBOL_FEMENINO', 'Fútbol de Campo Femenino'), ('FUTBOL_MASCULINO', 'Fútbol de Campo Masculino'), ('FUTSAL_FEMENINO', 'Fútsal Femenino'), ('FUTSAL_MASCULINO', 'Fútsal Masculino'), ('HANDBALL_FEMENINO', 'Handball Femenino'), ('HANDBALL_MASCULINO', 'Handball Masculino'), ('VOLLEY_FEMENINO', 'Volley Femenino'), ('VOLLEY_MASCULINO', 'Volley Masculino'), ('BASKET_FEMENINO', 'Básquet Femenino'), ('BASKET_MASCULINO', 'Básquet Masculino'), ('FUTBOL_UNIVERSITARIO', 'Fútbol Universitario'), ('PIKI', 'Piki'), ('AJEDREZ', 'Ajedrez'), ('PING_PONG', 'Ping Pong')], max_length=50, null=True),
        ),
    ]
