# Generated by Django 3.2.21 on 2024-08-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpunca', '0004_auto_20240826_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidounca',
            name='minuto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partidounca',
            name='tipo',
            field=models.CharField(blank=True, choices=[('INICIO DEL PARTIDO', 'Inicio del partido'), ('PENDIENTE', 'Pendiente'), ('FINAL DEL PARTIDO', 'Fin del partido')], max_length=100, null=True),
        ),
    ]
