# Generated by Django 3.2.21 on 2024-08-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpunca', '0007_categoria1_categoria2_categoria3_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posicionunca',
            old_name='puntos_ciclismo',
            new_name='puntos_ciclismofem',
        ),
        migrations.AddField(
            model_name='posicionunca',
            name='puntos_ciclismomasc',
            field=models.IntegerField(default=0),
        ),
    ]
